### ISSUE TITLE
Array isn't inserted at the cursor's location

### ISSUE THREAD

**Issue by EmilePerron** [TanemApps/vscode-json-to-php-array#1]
Hey there!

First of all, thanks for this extension: it's something I have a use for just about every week, and having a simple extension for this is gonna be absolutely lovely.

The only issue I have noticed so far is that the PHP array is not inserted at the cursor's current location, but at the start of the file.

Here's an example:

https://user-images.githubusercontent.com/9383532/219901681-36b8b6d7-dd43-4231-ac98-ff7e70bbd083.mp4

**Comment by TanemApps** [comment]
@EmilePerron 
After reviewing it myself following LGTM, I found some lint errors, so I fixed them and released it as v1.1.1 !!

https://marketplace.visualstudio.com/items?itemName=TanemApps.json-to-php-array

Thank you for your pull request !!
